### ISSUE TITLE
Multiple Statis Applications but using only a single proxy?

### ISSUE THREAD

**Issue by Quantum-Sicarius** [CyCoreSystems/ari-proxy#41]
Hi,
I am not sure if I am missing something.

I am able to register 2 apps via Docker if I do this:
```
    environment:
        ARI_APPLICATION: app1,app2
        ARI_USERNAME: asterisk
        ARI_PASSWORD: asterisk
```

Asterisk will then show:
```
 Creating Stasis app 'app1'
 Creating Stasis app 'app2'
```

However, I can't seem to listen for those apps as the NATS events appear to be combined:
```
Received on [ari.event.app1,app2.00:d8:61:0c:d0:a5]: 
```

But the listeners are looking out for:
```
DBUG[07-15|21:29:21] listening for events                     subject=ari.event.app1.>
DBUG[07-15|21:29:21] listening for events                     subject=ari.event.app2.>
```

I am able to circumvent this by running 2 proxies but that doesn't seem right.

Can anybody point me in the right direction?

Kind regards,
Thomas.
